### ISSUE TITLE
Server crashes when digging mesesons components

### ISSUE THREAD

**Issue by GreenDirkfried** [aegroto/netherwars#1]
I just "tested" this problem at the online server "Nether Wars, 161.97.81.121, 3000", but it seems to me that the server crashes when digging up (connected? powered?) mesesons components.

How to reproduce: Build a circuit with two not-logic gates next to each other and connect them with mesecons wires (So that you have a circuit). Then dig up one of the logic gates.
Second method: place a lever one node away from a mesecons wire, so that it connects by bridging this node. Then break the lever. 
The server should crash in both cases.

Can you reproduce this?

**Comment by aegroto** [comment]
Hello! Thanks for the report. I am aware that sometimes the game crashes when digging mesecons components. Only buttons and levers seems to be affected, while plants and logic circuits should work properly. I will take a deeper look into that once I have some spare time, but you should be able to build your circuits by using plants without the game crashing.

**Comment by aegroto** [comment]
Should be fixed on master, @GreenDirkfried let me know if you ever experience the bug again.

**Comment by GreenDirkfried** [comment]
Thanks! It seems to be fixed now :-)
